"""Render ``services/<svc>/Dockerfile`` from one template (B17-T01).

    python deploy/docker/render_dockerfiles.py          # write
    python deploy/docker/render_dockerfiles.py --check  # CI: fail if any Dockerfile drifted

Every image: multi-stage (deps built in a throwaway stage), python:3.11-slim,
non-root uid 10001, read-only source tree, no compilers or pip cache in the
final layer, a HEALTHCHECK, and ``VG_DATA_DIR=/data`` as the only writable path.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class Svc:
    name: str
    cmd: str  # python -m module [args]
    ports: tuple[int, ...]
    health: str | None  # URL path on the first port, or None for workers
    torch: bool = False
    apt: tuple[str, ...] = ("libsndfile1",)


# Ports follow SOURCE_OF_TRUTH §11; each service's port env var is set to match in
# deploy/docker-compose.prod.yml and the k8s manifests.
SERVICES = [
    Svc(
        "api_gateway",
        "services.api_gateway.main",
        (8080, 50050),
        "/healthz",
        torch=True,
        apt=("libsndfile1", "ffmpeg"),
    ),
    Svc("inference", "services.inference.main", (50052,), "/healthz", torch=True),
    Svc("privacy", "services.privacy.main serve", (8095,), "/healthz"),
    Svc("ingest", "services.ingest.main", (8081,), None, apt=("libsndfile1", "ffmpeg")),
    Svc("conditioner", "services.conditioner.main", (50051,), None),
    Svc("fusion", "services.fusion.main", (50053,), None),
    Svc("context", "services.context.main", (50054,), None, torch=True),
    Svc("policy", "services.policy.main", (8085,), None),
    Svc("enrollment", "services.enrollment.main", (8086,), None, torch=True),
]

TEMPLATE = """# syntax=docker/dockerfile:1.7
# GENERATED by deploy/docker/render_dockerfiles.py — edit the template, not this file.
# VoiceGuard {name} (B17-T01). Build from the repository root:
#   docker build -f services/{name}/Dockerfile -t voiceguard/{name}:$(git rev-parse --short HEAD) .

# ---- stage 1: dependencies (compilers live and die here) --------------------------
FROM python:3.11-slim AS deps
ENV PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1
RUN apt-get update \\
 && apt-get install -y --no-install-recommends build-essential \\
 && rm -rf /var/lib/apt/lists/*
RUN python -m venv /opt/venv
ENV PATH=/opt/venv/bin:$PATH
COPY pyproject.toml /tmp/pyproject.toml
RUN python -c "import tomllib, subprocess, sys; \\
d = tomllib.load(open('/tmp/pyproject.toml', 'rb'))['project']['dependencies']; \\
subprocess.check_call([sys.executable, '-m', 'pip', 'install', *d])"
{torch_line}
# ---- stage 2: runtime -------------------------------------------------------------
FROM python:3.11-slim AS runtime
RUN apt-get update \\
 && apt-get install -y --no-install-recommends {apt} \\
 && rm -rf /var/lib/apt/lists/* \\
 && groupadd --system --gid 10001 vg \\
 && useradd --system --uid 10001 --gid vg --home-dir /app --shell /usr/sbin/nologin vg \\
 && mkdir -p /data && chown vg:vg /data
COPY --from=deps /opt/venv /opt/venv
WORKDIR /app
# source is owned by root and read-only for the service user
COPY packages ./packages
COPY services ./services
COPY ml ./ml
COPY sdks ./sdks
COPY schemas ./schemas
COPY proto ./proto
COPY config ./config
ENV PATH=/opt/venv/bin:$PATH \\
    PYTHONPATH=/app \\
    PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    VG_DATA_DIR=/data
USER 10001:10001
VOLUME ["/data"]
EXPOSE {ports}
{healthcheck}
ENTRYPOINT ["python", "-m", {cmd}]
"""


def render(s: Svc) -> str:
    torch_line = (
        "RUN pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu\n"
        if s.torch
        else ""
    )
    health = (
        f"HEALTHCHECK --interval=15s --timeout=3s --start-period=60s --retries=3 \\\n"
        f"  CMD python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:{s.ports[0]}{s.health}', timeout=2)\""
        if s.health
        else "HEALTHCHECK NONE"
    )
    parts = s.cmd.split()
    cmd = ", ".join(f'"{p}"' for p in parts)
    return TEMPLATE.format(
        name=s.name,
        torch_line=torch_line,
        apt=" ".join(s.apt),
        ports=" ".join(str(p) for p in s.ports),
        healthcheck=health,
        cmd=cmd,
    )


def main(argv: list[str] | None = None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    drift = []
    for s in SERVICES:
        path = ROOT / "services" / s.name / "Dockerfile"
        text = render(s)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                drift.append(str(path))
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
    if drift:
        print(
            "Dockerfiles out of date (run deploy/docker/render_dockerfiles.py):", *drift, sep="\n  "
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
